// This file is automatically generated by NUCLEUS framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Nucleus.Application.Dtos;
using Nucleus.Http.Client;
using Nucleus.Http.Modeling;
using Nucleus.DependencyInjection;
using Nucleus.Http.Client.ClientProxying;
using Nucleus.AspNetCore.Mvc.MultiTenancy;

// ReSharper disable once CheckNamespace
namespace Pages.Nucleus.MultiTenancy.ClientProxies
{
    [Dependency(ReplaceServices = true)]
    [ExposeServices(typeof(INucleusTenantAppService), typeof(NucleusTenantClientProxy))]
    public partial class NucleusTenantClientProxy : ClientProxyBase<INucleusTenantAppService>, INucleusTenantAppService
    {
        public virtual async Task<FindTenantResultDto> FindTenantByNameAsync(string name)
        {
            return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByNameAsync), new ClientProxyRequestTypeValue
            {
                { typeof(string), name }
            });
        }

        public virtual async Task<FindTenantResultDto> FindTenantByIdAsync(Guid id)
        {
            return await RequestAsync<FindTenantResultDto>(nameof(FindTenantByIdAsync), new ClientProxyRequestTypeValue
            {
                { typeof(Guid), id }
            });
        }
    }
}






